"""Generate `requirements.txt` for the Vercel deployment from `uv.lock`.

Vercel's Python runtime installs from `requirements.txt` and does not read `pyproject.toml` or
`uv.lock`, so the deployed dependency set is a second declaration of the same thing. Generating
it rather than maintaining it is what keeps the two from drifting — a hand-written file agrees
with the lockfile right up until somebody upgrades one of them.

    uv run python scripts/vercel_requirements.py           # write requirements.txt
    uv run python scripts/vercel_requirements.py --check   # fail if it is stale

The server is dropped on the way through. Vercel runs the ASGI app itself, so `uvicorn` and the
C extensions its `[standard]` extra pulls in — uvloop, httptools, watchfiles — would be dead
weight in a bundle with a hard size limit, and `pandas` and `numpy` have already spent most of
it.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "requirements.txt"

#: Dropped from the export. Vercel provides the server; these only carry the dev one.
EXCLUDED = frozenset({"uvicorn", "uvloop", "httptools", "watchfiles", "websockets", "click"})

HEADER = """\
# Generated by scripts/vercel_requirements.py from uv.lock. Do not edit by hand.
#
# Vercel's Python runtime installs from this file and never sees pyproject.toml or uv.lock, so
# regenerate it whenever the lockfile moves:
#
#     uv run python scripts/vercel_requirements.py
#
# The ASGI server is deliberately absent — Vercel runs the app itself, and uvicorn's C
# extensions would be dead weight in a bundle that pandas and numpy have already half filled.
"""


def _package(line: str) -> str:
    return line.split("==")[0].split(" ")[0].strip().lower()


def render() -> str:
    export = subprocess.run(
        [
            "uv",
            "export",
            "--no-dev",
            "--extra",
            "dashboard",
            "--no-hashes",
            "--no-emit-project",
            "--format",
            "requirements-txt",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout

    kept = [
        line.rstrip()
        for line in export.splitlines()
        if line.strip() and not line.lstrip().startswith("#") and _package(line) not in EXCLUDED
    ]
    return HEADER + "\n" + "\n".join(kept) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args(argv)

    wanted = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != wanted:
            print(
                "requirements.txt is stale; run `uv run python scripts/vercel_requirements.py`",
                file=sys.stderr,
            )
            return 1
        print(f"ok: requirements.txt matches uv.lock ({len(wanted.splitlines())} lines)")
        return 0

    TARGET.write_text(wanted, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
